// Generated by CoffeeScript 1.10.0
(function() {
  var RESULTS_LIST_URL, RESULT_BASE_URL, app;

  RESULTS_LIST_URL = 'https://raw.githubusercontent.com/langmark/langmark/pushes/results.txt';

  RESULT_BASE_URL = 'https://raw.githubusercontent.com/langmark/langmark/pushes/results/';

  app = angular.module('langmark', []);

  app.controller('MainController', [
    '$scope', '$http', function($scope, $http) {
      var parseDate;
      $scope.analyzers = {};
      $scope.currentAnalyzer = null;
      $scope.currentFile = null;
      $scope.files = [];
      $http.get(RESULTS_LIST_URL).then(function(response) {
        var file, i, last, len, results;
        results = response.data.split("\n").filter(function(x) {
          return x !== "" && x[0] !== '#';
        });
        for (i = 0, len = results.length; i < len; i++) {
          file = results[i];
          $scope.analyzers[file] = new Analyzer(RESULT_BASE_URL + file, "[Travis] " + (parseDate(file)));
          $scope.files.push({
            name: "[Travis] " + (parseDate(file)),
            file: file
          });
        }
        last = $scope.files[$scope.files.length - 1];
        $scope.currentFile = last;
        return $scope.loadData(last.file);
      });
      $scope.loadData = function(index) {
        if (index == null) {
          index = $scope.currentFile.file;
        }
        return $scope.analyzers[index].loadData($http, true, function() {
          $scope.analyzers[index].draw();
          return $scope.currentAnalyzer = $scope.analyzers[index];
        });
      };
      return parseDate = function(date) {
        var day, hour, min, month, sec, year;
        year = date.slice(0, 4);
        month = date.slice(4, 6);
        day = date.slice(6, 8);
        hour = date.slice(8, 10);
        min = date.slice(10, 12);
        sec = date.slice(12, 14);
        return day + "/" + month + "/" + year + " at " + hour + ":" + min + ":" + sec;
      };
    }
  ]);

}).call(this);
